# Generated by Django 4.2.2 on 2023-06-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
